config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root "products#index"

  get "/carts/:id", to:"carts#show", as: "carts"
  
  post "line_items_buy_now/:product_id", to: "line_items#buy_now", as: "line_item_buy_now"
  post "line_items_add_to_cart/:product_id", to: "line_items#add_to_cart", as: "line_item_add_to_cart"
  post "line_items_add_quantity/:product_id", to: "line_items#add_quantity", as: "line_item_add_quantity"
  post "line_items_subtract_quantity/:product_id", to: "line_items#subtract_quantity", as: "line_item_subtract_quantity"
  get "add_product_from_index/:product_id", to: "line_items#add_product_from_index", as: "add_product_from_index"
  post "line_items_add_to_cart_from_index/:product_id", to: "line_items#add_to_cart_from_index", as: "line_item_add_to_cart_from_index"



  get "customer_address", to: "customers#customer_address", as:"customer_address"
  get "customer_address_turbo", to: "customers#customer_address_turbo", as:"customer_address_turbo"

  post "/order", to: "orders#order", as: "order"
  get "/success", to: "orders#success", as: "success"
  get "/orders", to: "orders#index", as: "orders"
  get "/order/:order_id", to: "orders#show", as: "order_show"


  post "customer_address_update", to: "customers#customer_address_update", as:"customer_address_update"

  delete "line_item_delete_from_cart/:product_id", to: "line_items#destroy_from_cart", as: "destroy_from_cart"

  post "/delivered/:order_id", to: "orders#mark_delivered", as: "mark_delivered"
  get "/orders/marked", to: "orders#index_marked", as: "index_marked"

  post "/undelivered/:order_id", to: "orders#mark_undelivered", as: "mark_undelivered"

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy

  enum status: { pending: 0, delivered: 1 }

  def total
    sum = 0
    self.line_items.each do |line_item|
      sum += line_item.total_of_single_product
    end
    return sum
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def order
    order = Order.create
    order.user = current_user
    @current_cart.line_items.each do |line_item|
      order.line_items << line_item
    end
    order.save!
    new_cart = Cart.create(user: current_user)
    session[:cart_id] = nil
  end

  def success

  end

  def index
    if current_user.try(:type)
      @orders = Order.where(status: 0)
    else
      @orders = current_user.orders
    end
  end

  def show
    @order = Order.find(params[:order_id])
  end

  def index_marked
    @orders = Order.where(status: 1)

  end

  def mark_delivered
    @orders = Order.where(status: 0)
    @order = Order.find(params[:order_id])
    @order.delivered!
    flash.now[:notice] = "Order-#{@order.id} Marked Delivered."
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream:
        [
          turbo_stream.update(
            "admin_orders",
            partial: "orders/admin_orders",
            locals: {order: @order}
          ),
          turbo_stream.update(
            "flash_#{current_user&.id}",
            partial: "layouts/flash",
          )
        ]
      }
    end
  end

  def mark_undelivered
    @orders = Order.where(status: 1)
    @order = Order.find(params[:order_id])
    @order.pending!
    flash.now[:alert] = "Order-#{@order.id} Marked Un-Delivered."
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream:
        [

          turbo_stream.update(
            "admin_orders_delivered",
            partial: "orders/admin_orders_delivered"
          ),
          turbo_stream.update(
            "flash_#{current_user&.id}",
            partial: "layouts/flash",
          )
        ]
      }
    end
  end

end

app/views/orders/_admin_orders.html.erb
<div class="flex items-center gap-[60px] border-slate-200 border-b-2 p-1">
  <h3 class="font-bold text-gray-700 text-lg">Order#</h3>
  <h3 class="font-bold text-gray-700 text-lg">Customer</h3>
  <h3 class="font-bold text-gray-700 text-lg">Products</h3>
  <h3 class="font-bold text-gray-700 text-lg">Date</h3>
  <h3 class="font-bold text-gray-700 text-lg">Amount Paid</h3>
  <h3 class="font-bold text-gray-700 text-lg">Mark Delivered?</h3>
  <h3 class="font-bold text-gray-700 text-lg">View Details</h3>

</div>

<div>
  <% @orders.each do |order| %>
    <div class="flex items-center gap-[66px] border-slate-200 border-b-2 p-2">
      <h3>Order#<%= order.id %></h3>
      <h3><%= order.user.email %></h3>
      <h3><%= order.line_items.size %></h3>
      <h3><%= order.created_at.strftime("%d-%m-%Y") %></h3>
      <h3 class="text-emerald-500">&#8377;<%= order.total %></h3>
      <%= button_to "Mark Delivered", mark_delivered_path(order), method: :post, class:"text-white bg-blue-600 px-2 py-1 rounded-md hover:bg-blue-700" %>
      <%= link_to "Details", order_show_path(order), class:"bg-gray-200 hover:bg-gray-300 px-2 py-1 rounded-md" %>
    </div>

  
  <% end %>
  
</div>

app/views/orders/_admin_orders_delivered.html.erb
<div class="flex items-center gap-[60px] border-slate-200 border-b-2 p-1">
  <h3 class="font-bold text-gray-700 text-lg">Order#</h3>
  <h3 class="font-bold text-gray-700 text-lg">Customer</h3>
  <h3 class="font-bold text-gray-700 text-lg">Products</h3>
  <h3 class="font-bold text-gray-700 text-lg">Date</h3>
  <h3 class="font-bold text-gray-700 text-lg">Amount Paid</h3>
</div>

<div>
  <% @orders.each do |order| %>
    <div class="flex items-center gap-[66px] border-slate-200 border-b-2 p-2">
      <h3>Order#<%= order.id %></h3>
      <h3><%= order.user.email %></h3>
      <h3><%= order.line_items.size %></h3>
      <h3><%= order.created_at.strftime("%d-%m-%Y") %></h3>
      <h3 class="text-emerald-500">&#8377;<%= order.total %></h3>
      <%= button_to "Mark Un-Delivered", mark_undelivered_path(order), method: :post, class:"text-white bg-red-600 px-2 py-1 rounded-md hover:bg-red-700" %>
    </div>

  
  <% end %>
  
</div>

app/views/orders/index.html.erb
<% if current_user.try(:type) %>
  <div class="grid place-items-end px-[60px]"><%= link_to "Marked Deliveries", index_marked_path, class:"text-blue-700 hover:text-blue-900" %></div>
  <div class="grid place-items-center mt-[50px]" id="admin_orders">
    <%= render "orders/admin_orders" %>
  </div>  

<% else %>

  <div class="bg-gray-50 py-12 w-screen leading-6">
    <div class="mx-auto px-4 sm:px-6 lg:px-8"> 

      <p class="mt-5 text-lg font-bold leading-7 text-gray-800">Your Orders</p>

      <hr class="mt-8 border-t border-gray-300" />
    </div>

    <% @orders.each do |order| %>
      <%= link_to order_show_path(order) do %>
        <div class="grid place-items-start p-10 bg-gray-100 hover:bg-gray-200 my-2">
          <h2 class="text-2xl font-extrabold text-gray-700 ">Order - <%= order.id %></h2>
          <h2>Products: <%= order.line_items.size %></h2>
        </div>
      <% end %>
      
      
    <% end %>
    
  </div>

<% end %>

app/views/orders/index_marked.html.erb
<div class="grid place-items-end px-[60px]"><%= link_to "Back", orders_path, class:"text-blue-700 hover:text-blue-900" %></div>

<div class="grid place-items-center" id="admin_orders_delivered">
  <%= render "admin_orders_delivered" %>
</div>

app/views/orders/show.html.erb
  <section class="flex items-center py-16 bg-gray-50 font-poppins dark:bg-gray-800 ">
        <div
            class="justify-center flex-1 max-w-4xl px-6 py-6 mx-auto bg-gray-100 rounded-md shadow-md dark:border-gray-900 dark:bg-gray-900 lg:py-10 lg:px-10">
            <div class="mb-16 text-center">
                <h1
                    class="mb-6 text-2xl font-semibold leading-7 tracking-wide text-gray-700 lg:text-4xl dark:text-gray-300 lg:leading-9">
                    Thank you for your Order, <%= current_user.email %></h1>
                <p class="text-lg text-gray-500 dark:text-gray-400">your order number is #<%= @order.id %></p>
            </div>
            <div class="max-w-4xl mx-auto mb-10">
                <h2 class="mb-4 text-xl font-medium dark:text-gray-400">What you ordered:</h2>
                <% @order.line_items.each do |line_item| %>
                
                
                <div
                    class="p-10 mb-8 bg-white rounded-md shadow dark:bg-gray-800 sm:flex sm:items-center xl:py-5 xl:px-12">
                    <a href="#" class="mr-6 md:mr-12">
                      <%= image_tag line_item.product.images[0], class:" w-full lg:w-[80px] h-[200px] lg:h-[80px]  object-cover  mx-auto mb-6 sm:mb-0 " %>
                    </a>
                    <div>
                        <a class="inline-block mb-1 text-lg font-medium hover:underline dark:text-gray-400" href="#">
                            <%= line_item.product.name %></a>
                        <div class="flex flex-wrap gap-4">
                          <p class="text-sm font-medium dark:text-gray-400">
                                <span>Price:</span>
                                <span class="ml-2 text-gray-400">&#x20B9;<%= line_item.product.price %></span>
                            </p>
                            <p class="text-sm font-medium dark:text-gray-400">
                                <span>Qty:</span>
                                <span class="ml-2 text-gray-400"><%= line_item.quantity %></span>
                            </p>
                            <p class="mr-4 text-sm font-medium">
                                <span class="font-medium dark:text-gray-400">Description:</span>
                                <span class="ml-2 text-gray-400 dark:text-gray-400"><%= line_item.product.description.truncate(70) %></span>
                            </p>
                        </div>
                    </div>
                </div>
                <% end %>
                    <div
                        class="flex items-center gap-4 px-10 py-3 font-medium leading-8 bg-white rounded-md shadow dark:text-gray-400 dark:bg-gray-800 font-heading">
                        <h3>Address:</h3>
                        <span class="flex items-center text-blue-500 dark:text-blue-400">
                            <span class="text-xl"><%= @order.user.address %></span>
                        </span>
                    </div>
            </div>
            <div class="max-w-4xl mx-auto ">
                <h2 class="mb-4 text-xl font-medium dark:text-gray-400 ">Order Details:</h2>
                <div class="grid place-items-center">
                  <div class="flex flex-row justify-between gap-5">

                    <div
                        class="relative flex items-center justify-between px-10 py-3 font-medium leading-8 bg-white bg-opacity-50 rounded-md shadow dark:text-gray-400 dark:bg-gray-800">
                        <div
                            class="absolute right-0 flex items-center justify-center bg-blue-500 rounded-md w-14 h-14 dark:bg-gray-600">
                            <div
                                class="flex items-center justify-center text-lg font-bold text-blue-500 bg-gray-100 rounded-full dark:text-gray-300 dark:bg-gray-700 w-11 h-11">
                                <%= @order.line_items.size %></div>
                        </div>
                        <span class="mr-16">Products</span>
                    </div>
                    <div
                        class="flex items-center justify-between px-10 py-3 font-medium leading-8 bg-white rounded-md shadow dark:text-gray-400 dark:bg-gray-800 font-heading">
                        <span>Total</span>
                        <span class="flex items-center text-blue-500 dark:text-blue-400">
                            <span class="ml-3 mr-1 text-sm">Rs.</span>
                            <span class="text-xl"><%= @order.total %></span>
                        </span>
                    </div>
                  </div>
                </div>
                <div class="flex flex-wrap items-center justify-between gap-4 ">
                  <%= link_to "Go back shopping", products_path, class:"w-full px-6 py-3 text-blue-500 border border-blue-500 rounded-md md:w-auto hover:text-gray-100 hover:bg-blue-600 dark:border-gray-800 dark:hover:bg-gray-800 dark:text-gray-300" %>

                  <%= link_to "Back to orders", orders_path, class:"w-full px-6 py-3 text-red-500 border border-red-500 rounded-md md:w-auto hover:text-gray-100 hover:bg-red-600 dark:border-gray-800 dark:hover:bg-gray-800 dark:text-gray-300"  %>
           
                </div>
            </div>

        </div>
    </section>

app/views/orders/success.html.erb
<%= content_for :success do %>
 <section class="flex items-center h-screen bg-white font-poppins dark:bg-gray-800 ">
    <div class="justify-center flex-1 px-6 py-16 mx-auto lg:py-16 md:px-7">
        <div
            class="max-w-xl p-8 mx-auto border rounded-md bg-gradient-to-r from-blue-50 to-gray-50 dark:from-gray-900 dark:to-gray-900 dark:border-gray-900 dark:bg-gray-900">
            <h2 class="mb-4 text-4xl font-extrabold tracking-wide dark:text-gray-300">Thank you for your order !
            </h2>
           
            <%= link_to "View Orders", orders_path, class:"text-blue-500 hover:underline dark:text-blue-400 hover:text-blue-700" %>
        </div>
    </div>
</section>
<% end %>