config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root "products#index"

  get "/carts/:id", to:"carts#show", as: "carts"
  
  post "line_items_buy_now/:product_id", to: "line_items#buy_now", as: "line_item_buy_now"
  post "line_items_add_to_cart/:product_id", to: "line_items#add_to_cart", as: "line_item_add_to_cart"
  post "line_items_add_quantity/:product_id", to: "line_items#add_quantity", as: "line_item_add_quantity"
  post "line_items_subtract_quantity/:product_id", to: "line_items#subtract_quantity", as: "line_item_subtract_quantity"
  get "add_product_from_index/:product_id", to: "line_items#add_product_from_index", as: "add_product_from_index"
  post "line_items_add_to_cart_from_index/:product_id", to: "line_items#add_to_cart_from_index", as: "line_item_add_to_cart_from_index"



  get "customer_address", to: "customers#customer_address", as:"customer_address"
  get "customer_address_turbo", to: "customers#customer_address_turbo", as:"customer_address_turbo"

  post "/order", to: "orders#order", as: "order"
  get "/success", to: "orders#success", as: "success"
  get "/orders", to: "orders#index", as: "orders"
  get "/order/:order_id", to: "orders#show", as: "order_show"


  post "customer_address_update", to: "customers#customer_address_update", as:"customer_address_update"

  delete "line_item_delete_from_cart/:product_id", to: "line_items#destroy_from_cart", as: "destroy_from_cart"

  post "/delivered/:order_id", to: "orders#mark_delivered", as: "mark_delivered"
  get "/orders/marked", to: "orders#index_marked", as: "index_marked"

  post "/undelivered/:order_id", to: "orders#mark_undelivered", as: "mark_undelivered"

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :line_items, dependent: :destroy # current_cart.line_items
  has_many :products, through: :line_items # current_cart.products

  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum += line_item.total_of_single_product
    end
    return sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    @cart = @current_cart
  end
end

app/views/carts/_address.html.erb
<p>
  <span class="text-sm text-slate-900"><%= current_user.address %></span>
</p>

app/views/carts/_quantity.html.erb
<%= line_item.quantity %>

app/views/carts/_razorpay.html.erb
<% if cart.line_items.present? %>
  <% if cart.sub_total > 1  %>
    <% order = Razorpay::Order.create(amount: (cart.sub_total.to_i * 100), currency: 'INR', receipt: 'TEST') %>
  <% end %>
  <button data-controller="razorpay" razor-order-id="<%= order&.id %>" razor-amount="<%= cart.sub_total.to_i * 100 %>" id="rzp-button1" type="button" class="group inline-flex w-full items-center justify-center rounded-md bg-gray-900 px-6 py-4 text-lg font-semibold text-white transition-all duration-200 ease-in-out focus:shadow hover:bg-gray-800">
    Checkout
    <svg xmlns="http://www.w3.org/2000/svg" class="group-hover:ml-8 ml-4 h-6 w-6 transition-all" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13 7l5 5m0 0l-5 5m5-5H6" />
    </svg>
  </button>
<% end %>

app/views/carts/_sub_total.html.erb
&#x20B9;<%= cart.sub_total %>

app/views/carts/show.html.erb
<section class="h-screen py-12 sm:py-16 lg:py-20">
  <div class="mx-auto px-4 sm:px-6 lg:px-8">
    <div class="mx-auto mt-4 max-w-2xl md:mt-12">
      <div class="bg-white shadow">
        <div class="px-4 py-6 sm:px-8 sm:py-10">
          <div class="flow-root">
            <ul class="-my-8">
            <% @current_cart.line_items.each do |line_item| %>
              <li id="line_item_<%= line_item.id %>" class="flex flex-col space-y-3 py-6 text-left sm:flex-row sm:space-x-5 sm:space-y-0">
                <div class="shrink-0">
                  <%= image_tag line_item.product.images[0], class:"h-24 w-24 max-w-full rounded-lg object-cover" %>
                </div>

                <div class="relative flex flex-1 flex-col justify-between">
                  <div class="sm:col-gap-5 sm:grid sm:grid-cols-2">
                    <div class="pr-8 sm:pr-5">
                      <p class="text-base font-semibold text-gray-900"><%= line_item.product.name %></p>
                      <p class="mx-0 mt-1 mb-0 text-sm text-gray-400"><%= line_item.product.description.truncate(55) %></p>
                    </div>

                    <div class="mt-4 flex items-end justify-between sm:mt-0 sm:items-start sm:justify-end">
                      <p class="shrink-0 w-20 text-base font-semibold text-gray-900 sm:order-2 sm:ml-8 sm:text-right">&#x20B9;<%= line_item.product.price %></p>

                      <div class="sm:order-1">
                        <div class="mx-auto flex h-8 items-stretch text-gray-600">
                          <%= button_to "-", line_item_subtract_quantity_path(line_item.product), class:"flex items-center justify-center rounded-l-md bg-gray-200 px-4 transition hover:bg-black hover:text-white" %>
                          <div class="flex w-full items-center justify-center bg-gray-100 px-4 text-xs uppercase transition">
                            <%= turbo_frame_tag "quantity_#{line_item.id}" do %>
                              <%= render "quantity", line_item: line_item %>  
                            <% end %>
                          </div>
                          <%= button_to "+", line_item_add_quantity_path(line_item.product), class:"flex items-center justify-center rounded-r-md bg-gray-200 px-4 transition hover:bg-black hover:text-white" %>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="absolute top-0 right-0 flex sm:bottom-0 sm:top-auto">
                    <%= button_to destroy_from_cart_path(line_item.product), method: :delete, class:"flex rounded p-2 text-center text-gray-500 transition-all duration-200 ease-in-out focus:shadow hover:text-gray-900" do %>
                      <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" class=""></path>
                      </svg>
                    </button>
                    <% end %>
                  </div>
                </div>
              </li>
        
            <% end %>
            </ul>
          </div>

          <div class="mt-6 border-t border-b py-2">
            <div class="flex items-center justify-between">
              <p class="text-sm text-gray-400">Subtotal</p>
              <p class="text-lg font-semibold text-gray-900">
                <%= turbo_frame_tag "Cart_#{@cart.id}" do %>
                  <%= render "sub_total", cart: @cart %>
                <% end %>
              </p>
            </div>
          </div>

          <div class="grid place-items-center">
            <div class="group my-5 flex w-full max-w-xs flex-col overflow-hidden rounded-lg border border-gray-100 bg-white shadow-md">
                <div class="mt-4 px-5 pb-5">
                  <div class="flex items-center justify-between">
                    <h5 class="text-xl tracking-tight text-slate-900">Address</h5>
                    <%= link_to customer_address_turbo_path, data:{ controller: "wire"} do %>
                      <i class="fa-solid fa-pencil" style="color: red;"></i>
                    <% end %>
                  </div>
                  <div class="mt-2 mb-5" id="current_user_address<%=current_user.id%>">
                    <%= render "carts/address", current_user: current_user %>
                  </div>
              
                </div>
              </div>
          </div>

        <% if @cart.line_items.present? %>
          <div class="mt-6 text-center" id="checkout_btn_<%= current_user.id %>">
            <%= render "carts/razorpay", cart: @cart %>
          </div>
          <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
        <% end %>
        
        </div>
      </div>
    </div>
  </div>
</section>