config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  root "products#index"

  get "/carts/:id", to:"carts#show", as: "carts"
  
  post "line_items_buy_now/:product_id", to: "line_items#buy_now", as: "line_item_buy_now"
  post "line_items_add_to_cart/:product_id", to: "line_items#add_to_cart", as: "line_item_add_to_cart"
  post "line_items_add_quantity/:product_id", to: "line_items#add_quantity", as: "line_item_add_quantity"
  post "line_items_subtract_quantity/:product_id", to: "line_items#subtract_quantity", as: "line_item_subtract_quantity"
  get "add_product_from_index/:product_id", to: "line_items#add_product_from_index", as: "add_product_from_index"
  post "line_items_add_to_cart_from_index/:product_id", to: "line_items#add_to_cart_from_index", as: "line_item_add_to_cart_from_index"



  get "customer_address", to: "customers#customer_address", as:"customer_address"
  get "customer_address_turbo", to: "customers#customer_address_turbo", as:"customer_address_turbo"

  post "/order", to: "orders#order", as: "order"
  get "/success", to: "orders#success", as: "success"
  get "/orders", to: "orders#index", as: "orders"
  get "/order/:order_id", to: "orders#show", as: "order_show"


  post "customer_address_update", to: "customers#customer_address_update", as:"customer_address_update"

  delete "line_item_delete_from_cart/:product_id", to: "line_items#destroy_from_cart", as: "destroy_from_cart"

  post "/delivered/:order_id", to: "orders#mark_delivered", as: "mark_delivered"
  get "/orders/marked", to: "orders#index_marked", as: "index_marked"

  post "/undelivered/:order_id", to: "orders#mark_undelivered", as: "mark_undelivered"

end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images

  has_many :line_items, dependent: :destroy

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    if current_user.try(:type)
      @product = Product.new
    else
      redirect_to root_path
    end
  end

  def edit
    if current_user.try(:type)
    else
      redirect_to root_path
    end

  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_url(@product), notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_url(@product), notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_to_cart_form.html.erb
<%= form_with(url: line_item_add_to_cart_path(product), method: :post) do |form| %>
  <%= form.number_field :quantity %>
  <%= form.submit "Add", class:"bg-gray-200 p-2 hover:cursor-pointer hover:bg-gray-300 transition:ease-in duration-300" %>
<% end %>

app/views/products/_form.html.erb
<div class="grid place-items-center">

  <div class="bg-blue-700 p-[9px] shadow-md hover:shadow-xl transition:eas-in duration-500 rounded-sm">

    <div class="bg-white p-12">
      

      <%= form_with(model: product) do |form| %>
        <% if product.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
              <% product.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :name, style: "display: block", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= form.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 md:w-96" %>
        </div>

        <div>
          <%= form.label :description, style: "display: block", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= form.text_area :description, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 md:w-96" %>
        </div>

        <div>
          <%= form.label :price, style: "display: block", class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= form.number_field :price, min: 0, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 md:w-96" %>
        </div>
          
        <div>
          <%= form.file_field :images, multiple: true, class:"my-6" %>
        </div>
        
        <div>
          <%= form.submit class:"text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 hover:cursor-pointer my-4"  %>
        </div>
      <% end %>

      
      <div>
        <%= link_to "Back to products", products_path %>
      </div>

    </div>

  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

app/views/products/edit.html.erb
<h1 class="text-2xl font-extrabold text-gray-700 mb-5 text-center">Edit product</h1>

<%= render "form", product: @product %>

<br>

app/views/products/index.html.erb
<div id="products" class="grid grid-cols-4 place-items-center">
  <% @products.each do |product| %>
    <div class="group my-10 flex w-full max-w-xs flex-col overflow-hidden rounded-lg border border-gray-100 bg-white shadow-md">
      <%= link_to product_path(product), class:"relative mx-3 mt-3 flex h-60 overflow-hidden rounded-xl" do %>
        
        <%= image_tag product.images[0], class:"peer absolute top-0 right-0 h-full w-full object-cover" %>
        <%= image_tag product.images[1], class:"peer absolute top-0 -right-96 h-full w-full object-cover transition-all delay-100 duration-1000 hover:right-0 peer-hover:right-0" %>
        <!-- <div class="absolute  bottom-0 mb-4 flex space-x-4 w-full justify-center">
          <div class="rounded-full h-3 w-3 bg-gray-200 border-2 border-white"></div> 
          <div class="rounded-full h-3 w-3 bg-gray-200 border-2 border-white"></div>
          <div class="rounded-full h-3 w-3 bg-gray-200 border-2 border-white"></div>
        </div> -->
        <svg class="pointer-events-none absolute inset-x-0 bottom-5 mx-auto text-3xl text-white  transition-opacity group-hover:animate-ping group-hover:opacity-30 peer-hover:opacity-0" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 32 32"><path fill="currentColor" d="M2 10a4 4 0 0 1 4-4h20a4 4 0 0 1 4 4v10a4 4 0 0 1-2.328 3.635a2.996 2.996 0 0 0-.55-.756l-8-8A3 3 0 0 0 14 17v7H6a4 4 0 0 1-4-4V10Zm14 19a1 1 0 0 0 1.8.6l2.7-3.6H25a1 1 0 0 0 .707-1.707l-8-8A1 1 0 0 0 16 17v12Z" /></svg>
        <!-- <span class="absolute top-0 left-0 m-2 rounded-full bg-black px-2 text-center text-sm font-medium text-white">39% OFF</span> -->
      <% end %>
      
      <div class="mt-4 px-5 pb-5">
        <a href="#">
          <h5 class="text-xl tracking-tight text-slate-900"><%= product.name %></h5>
        </a>
        <div class="mt-2 mb-5 flex items-center justify-between">
          <p>
            <span class="text-3xl font-bold text-slate-900"> &#x20B9;<%= product.price %></span><br>
            <span class="text-sm text-slate-900"><%= product.description.truncate(83) %></span>
          </p>
        </div>

        
        <% if current_user %>
          
          
          <%= turbo_frame_tag "product_#{product.id}_user_#{current_user&.id}" do %>
            <%= link_to add_product_from_index_path(product), data:{controller:"wire"}, class:"flex items-center justify-center rounded-md bg-slate-900 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-blue-300" do %>
          
          
            <svg xmlns="http://www.w3.org/2000/svg" class="mr-2 h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            Add to cart
            <% end %>
          
          <% end %>

        <% else %>
          <%= link_to new_user_session_path, class:"flex items-center justify-center rounded-md bg-slate-900 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-blue-300" do %>
          
            <svg xmlns="http://www.w3.org/2000/svg" class="mr-2 h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            Add to cart
            <% end %>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/products/new.html.erb
<h1 class="text-2xl font-extrabold text-gray-700 mb-5 text-center">New product</h1>
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="dark:bg-gray-800 py-8">
    <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex flex-col md:flex-row -mx-4">
            <div class="md:flex-1 px-4">
                <div class="rounded-lg bg-gray-300 dark:bg-gray-700 mb-4">
                  <div id="indicators-carousel" class="relative w-full" data-carousel="static">
                      <!-- Carousel wrapper -->
                      <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
                          <% @product.images.each_with_index do |image, index| %>
                          <!-- Item 1 -->
                            <div class="<%= index.zero? ? "active" : "hidden" %>" data-carousel-item="<%= index %>">
                              <%= image_tag image, class:"absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" %>
                            </div>
                          <% end %>
                      </div>

                      <!-- Slider indicators -->
                      <div class="absolute z-30 flex -translate-x-1/2 space-x-3 rtl:space-x-reverse bottom-5 left-1/2">
                        <% @product.images.each_with_index do |_, index| %>
                          <button type="button" class="w-3 h-3 rounded-full" aria-current="<%= index.zero? %>" aria-label="Slide <%= index + 1 %>" data-carousel-slide-to="<%= index %>"></button>
                        <% end %>
                      </div>
                      <!-- Slider controls -->
                      <button type="button" class="absolute top-0 start-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
                          <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                              <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
                              </svg>
                              <span class="sr-only">Previous</span>
                          </span>
                      </button>
                      <button type="button" class="absolute top-0 end-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
                          <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-white/30 dark:bg-gray-800/30 group-hover:bg-white/50 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                              <svg class="w-4 h-4 text-white dark:text-gray-800 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                              </svg>
                              <span class="sr-only">Next</span>
                          </span>
                      </button>
                  </div>

                </div>
            </div>
            <div class="md:flex-1 px-4">
                <h2 class="text-2xl font-bold text-gray-800 dark:text-white mb-2"><%= @product.name %></h2>
                <div class="flex mb-4">
                    <div class="mr-4">
                        <span class="font-bold text-gray-700 dark:text-gray-300">Price:</span>
                        <span class="text-gray-600 dark:text-gray-300"> &#x20B9;<%= @product.price %></span>
                    </div>
            
                </div>
         
                <div>
                    <span class="font-bold text-gray-700 dark:text-gray-300">Product Description:</span>
                    <p class="text-gray-600 dark:text-gray-300 text-sm mt-2">
                      <%= @product.description %>
                    </p>
                </div>
                <div class="flex -mx-2 mb-4 mt-5">
                    <div class="w-1/2 px-2">
                      
                      <% if current_user  %>
                        <%= button_to "Buy Now", line_item_buy_now_path(@product), data: {turbo: false} , class:"w-full bg-gray-900 dark:bg-gray-600 text-white py-2 px-4 rounded-full font-bold hover:bg-gray-800 dark:hover:bg-gray-700 transition:ease-in duration-300"%>
                      <% else %>
                        <%= button_to "Buy Now", new_user_session_path, data: {turbo: false} , class:"w-full bg-gray-900 dark:bg-gray-600 text-white py-2 px-4 rounded-full font-bold hover:bg-gray-800 dark:hover:bg-gray-700 transition:ease-in duration-300"%>
                      <% end %>
                      
                    </div>
                    <div class="w-1/2 px-2" id="add_to_cart_<%= current_user&.id %>">
                    <% if current_user  %>
                      <%= render "products/add_to_cart_form", product: @product %>
                    <% end %>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="grid place-items-start p-10">
  <div class="grid grid-cols-3 gap-4">

    <%= link_to "Back to products", products_path, class:"bg-gray-100 p-2 text-black hover:bg-gray-200" %>
    <% if current_user.try(:type) %>
      <%= link_to "Edit this product", edit_product_path(@product), class:"bg-green-400 p-2 text-white hover:bg-green-700" %> 
      <%= button_to "Destroy this product", @product, method: :delete, class:"bg-red-400 p-2 text-white hover:bg-red-700" %>
    <% end %>
  </div>
</div>